<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!-- standalone ist optional, Standard-Wert ist "no" -->

<!DOCTYPE musiksammlung [
<!--  <!ENTITY ja "JÃ¶rg Aderhold"> -->


<!-- Root-Element             -->
<!ELEMENT musiksammlung (album+)>

<!-- Element der 2. Ebene     -->
<!ELEMENT album (label, (interpret|gruppe)+, titel, lied* )>

<!-- Elemente der 3. Ebene    -->
<!ELEMENT besitzer  (#PCDATA)>
<!ELEMENT label     (#PCDATA)>
<!ELEMENT interpret (#PCDATA)>
<!ELEMENT gruppe    (#PCDATA)>
<!ELEMENT titel     (#PCDATA)>
<!ELEMENT lied      (#PCDATA)>

]>

<musiksammlung>

  <album>
    <label>Mute Records Limited</label>
    <interpret>Moby</interpret>
    <titel>Play</titel>
    <lied>Honey</lied>
    <lied>Find my baby</lied>
    <lied>Porcelain</lied>
    <lied>Why does my heart feel so bad?</lied>
    <lied>South side</lied>
    <lied>Rushing</lied>
    <lied>Bodyrock</lied>
    <lied>Natural Blues</lied>
    <lied>Machete</lied>
  </album>

  <album>
    <label>Sony Music</label>
    <gruppe>a-ha</gruppe>
    <titel>Minor earth and major sky</titel>
    <lied>Minor earth and major sky</lied>
    <lied>Little black</lied>
    <lied>...</lied>
  </album>

  <album>
    <label>T-Summer Ltd.</label>
    <interpret>Mesh</interpret>
    <titel>Fragmente</titel>
    <lied>Trust on you</lied>
    <lied>My defender</lied>
    <lied>...</lied>
  </album>

</musiksammlung>